### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/monarch-ontology#17]
We should add the appropriate license to the README.

**Comment by drseb** [comment]
Might be problematic, because of the upstream licenses.

**Comment by matentzn** [comment]
You probably had this discussion 100 times, but are we certain that imports are actually proper parts and need to be considered for the license? So lets say I have a maven project and I import a package from Maven central, do I need to  adhere to the license restriction of that import for the GitHub repo, or only for the packaged software (there, the import is of course resolved, so physically bundled with the thing that is licensed). What about imports of imports? I will never have control over those..

**Comment by drseb** [comment]
I am not sure. I just thought I bring this up so that you are aware of the different and strange(HP) licenses in the imports.

**Comment by matentzn** [comment]
Close for now.
