### ISSUE TITLE
Monarch OWL resource consumption

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/monarch-ontology#23]
Moving email threat discussion here. 

First mistake I did and fixed is forgetting to use ROBOTs --preserve-structure false when removing owl:Nothing axioms. That was a MAJOR mistake, so checking now if we can move on further. @cmungall @balhoff @kltm 

Will ping you when we are ready to try again.

**Comment by matentzn** [comment]
@kshefchek When is it save to use our [Jenkis](https://ci.monarchinitiative.org/view/pipelines/job/monarch-owl-pipeline/) Job again?

@kltm `sh make SRC=mo-edit.owl preprocess_release -B` should now be relatively fast (30 min with 8GB of RAM). I am currently running some tests; you can try if you want.

**Comment by matentzn** [comment]
The last time I spoke to @kshefchek, this pipeline was used prior to Sci-Graph ingest:

```
java -jar owltools http://purl.obolibrary.org/obo/upheno/monarch.owl --merge-import-closure --remove-disjoints --remove-equivalent-to-nothing-axioms -o monarch-merged.owl
# Hack to resolve https://github.com/monarch-initiative/monarch-ontology/issues/16
sed -i '/owl#ReflexiveProperty/d' ./monarch-merged.owl
scp monarch-merged.owl monarch@monarch-ttl-prod:/var/www/data/owl/
```

So no reasoning involved. How ELK does not choke during sci-graph loading i con long wonder; I assume the preprocessing is somehow enough to avoid most unsats..

**Comment by cmungall** [comment]
Are we sure our SciGraph instance is configured to reason using Elk? @kshefchek ?

**Comment by kshefchek** [comment]
It is along with GENO,
https://github.com/monarch-initiative/scigraph-docker/blob/master/conf/ontology/monarchLoadConfiguration.yaml.tmpl#L18

**Comment by matentzn** [comment]
Since the build works now with no (memory) problem, closing this.
