### ISSUE TITLE
Investigate weird UBERON classes in the nifstd namespace.

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/monarch-ontology#27]
Just stumbled across this:

`grep http://uri.neuinfo.org/nif/nifstd/UBERON_ monarch-merged.owl`

```
<owl:equivalentClass rdf:resource="http://uri.neuinfo.org/nif/nifstd/UBERON_0000349"/>
        <oboInOwl:hasDbXref rdf:resource="http://uri.neuinfo.org/nif/nifstd/UBERON_0000349"/>
        <owl:equivalentClass rdf:resource="http://uri.neuinfo.org/nif/nifstd/UBERON_0001833"/>
        <oboInOwl:hasDbXref rdf:resource="http://uri.neuinfo.org/nif/nifstd/UBERON_0001833"/>
        <owl:equivalentClass rdf:resource="http://uri.neuinfo.org/nif/nifstd/UBERON_0001886"/>
        <oboInOwl:hasDbXref rdf:resource="http://uri.neuinfo.org/nif/nifstd/UBERON_0001886"/>
        <owl:equivalentClass rdf:resource="http://uri.neuinfo.org/nif/nifstd/UBERON_0002102"/>
        <oboInOwl:hasDbXref rdf:resource="http://uri.neuinfo.org/nif/nifstd/UBERON_0002102"/>
    <!-- http://uri.neuinfo.org/nif/nifstd/UBERON_0000349 -->
    <owl:Class rdf:about="http://uri.neuinfo.org/nif/nifstd/UBERON_0000349"/>
    <!-- http://uri.neuinfo.org/nif/nifstd/UBERON_0001833 -->
    <owl:Class rdf:about="http://uri.neuinfo.org/nif/nifstd/UBERON_0001833"/>
    <!-- http://uri.neuinfo.org/nif/nifstd/UBERON_0001886 -->
    <owl:Class rdf:about="http://uri.neuinfo.org/nif/nifstd/UBERON_0001886"/>
    <!-- http://uri.neuinfo.org/nif/nifstd/UBERON_0002102 -->
    <owl:Class rdf:about="http://uri.neuinfo.org/nif/nifstd/UBERON_0002102"/>
```

**Comment by matentzn** [comment]
This could insofar be weird as UBERON classes with those IDs already exist in UBERON itself; FYI @cmungall @nicolevasilevsky

**Comment by dosumis** [comment]
Yeh.  You may find FBbt fossils in there too.  This comes from various resources with neuro-anatomy terms being consumed for a NIF wiki some years back.  If we want NIF or its descendants in Monarch, we should talk to @tgbugs about how - as he now runs dynamic imports of Uberon etc.

**Comment by matentzn** [comment]
Thanks!

**Comment by cmungall** [comment]
David is correct. With uberon this was mostly classes like 'lip' where NIF
needed to reference a non-neuroanatomical concept (e.g. to talk of the lip
being innervated). For various legacy historic technical reasons they ended
up with these bogus URIs

I think the easiest thing to do is remove all these "fake" xrefs (we keep
the ones to actual nif concepts of course)

This doesn't even resolve anymore:
http://uri.neuinfo.org/nif/nifstd/UBERON_0001833

**Comment by cmungall** [comment]
there's only 4 of them...

**Comment by cmungall** [comment]
will be gone in next uberon release

**Comment by tgbugs** [comment]
For the record I think I already zapped all of these from our systems. They were as confusing for me as they were for everyone else.
